import { NextResponse } from "next/server";
import { eq } from "drizzle-orm";
import { cookies } from "next/headers";
import { db } from "@/db";
import { features, featureVideo } from "@/db/schema";
import { verifyAdminToken } from "@/lib/admin/auth";

export async function GET() {
  try {
    const adminCookie = (await cookies()).get("admin-session")?.value;
    const adminEmail = await verifyAdminToken(adminCookie);
    if (!adminEmail) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Get all features
    const allFeatures = await db.query.features.findMany();

    // Get all videos grouped by feature+locale
    const allVideos = await db.query.featureVideo.findMany();

    const result = allFeatures.map((feature) => {
      const videos = allVideos.filter(
        (v) => v.featureKey === feature.key
      );

      const daVideos = videos.filter((v) => v.locale === "da").sort((a, b) => b.version - a.version);
      const enVideos = videos.filter((v) => v.locale === "en").sort((a, b) => b.version - a.version);
      const daVideo = daVideos.find((v) => v.isCurrent) ?? daVideos[0] ?? null;
      const enVideo = enVideos.find((v) => v.isCurrent) ?? enVideos[0] ?? null;

      return {
        key: feature.key,
        name: feature.name,
        route: feature.route,
        da: daVideo
          ? {
              id: daVideo.id,
              version: daVideo.version,
              status: daVideo.status,
              title: daVideo.title,
              updatedAt: daVideo.updatedAt,
              videoPath: daVideo.videoPath,
            }
          : null,
        en: enVideo
          ? {
              id: enVideo.id,
              version: enVideo.version,
              status: enVideo.status,
              title: enVideo.title,
              updatedAt: enVideo.updatedAt,
              videoPath: enVideo.videoPath,
            }
          : null,
      };
    });

    return NextResponse.json(result);
  } catch (error) {
    console.error("Failed to fetch admin videos:", error);
    return NextResponse.json(
      { error: "Failed to fetch videos" },
      { status: 500 }
    );
  }
}

export async function POST(req: Request) {
  try {
    const adminCookie = (await cookies()).get("admin-session")?.value;
    const adminEmail = await verifyAdminToken(adminCookie);
    if (!adminEmail) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await req.json();
    const { featureKey, locale, title, videoPath, thumbnailPath, description, durationSeconds, autoShow, triggerType, goal } = body;

    // Validate required fields
    if (!featureKey || !locale || !title || !videoPath) {
      return NextResponse.json(
        { error: "Missing required fields: featureKey, locale, title, videoPath" },
        { status: 400 }
      );
    }

    if (locale !== "da" && locale !== "en") {
      return NextResponse.json(
        { error: "Locale must be 'da' or 'en'" },
        { status: 400 }
      );
    }

    // Check feature exists
    const feature = await db.query.features.findFirst({
      where: eq(features.key, featureKey),
    });

    if (!feature) {
      return NextResponse.json(
        { error: `Feature '${featureKey}' not found` },
        { status: 404 }
      );
    }

    // Calculate next version
    const existingVideos = await db.query.featureVideo.findMany({
      where: eq(featureVideo.featureKey, featureKey),
    });

    const maxVersion = Math.max(...existingVideos.map((v) => v.version), 0);
    const nextVersion = maxVersion + 1;

    // Insert new draft video (ID generated by DB)
    const now = new Date();

    const result = await db
      .insert(featureVideo)
      .values({
        featureKey,
        locale,
        title,
        description: description || null,
        videoPath,
        thumbnailPath: thumbnailPath || null,
        durationSeconds: durationSeconds || null,
        version: nextVersion,
        status: "draft",
        isCurrent: false,
        autoShow: autoShow ?? true,
        triggerType: triggerType || "auto",
        goal: goal || null,
        createdAt: now,
        updatedAt: now,
      })
      .returning({ id: featureVideo.id });

    return NextResponse.json(
      { id: result[0]?.id, version: nextVersion, status: "draft" },
      { status: 201 }
    );
  } catch (error) {
    console.error("Failed to create video:", error);
    return NextResponse.json(
      { error: "Failed to create video" },
      { status: 500 }
    );
  }
}
